
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDleftEQGTLTGELENEleftPLUSMINUSleftTIMESDIVIDEAND BOOL DIVIDE E EQ GE GT LE LPAREN LT MINUS NE NUMBER OR PI PLUS RPAREN TIMESexpression : expressionL\n                  | expressionAexpressionL : expressionL OR termL\n                   | termLtermL : termL AND factorL\n             | factorL factorL : BOOL\n               | factorA EQ factorA\n               | factorA GT factorA\n               | factorA LT factorA\n               | factorA GE factorA\n               | factorA LE factorA\n               | factorA NE factorA\n               | LPAREN expressionL RPARENexpressionA : expressionA PLUS termA\n                   | expressionA MINUS termA\n                   | termAtermA : termA TIMES factorA\n             | termA DIVIDE factorA\n             | factorA factorA : NUMBER\n               | PI\n               | E\n               | LPAREN expressionA RPAREN'
    
_lr_action_items = {'BOOL':([0,9,13,16,],[8,8,8,8,]),'LPAREN':([0,9,13,14,15,16,17,18,19,20,21,22,23,24,31,],[9,9,9,31,31,9,31,31,31,31,31,31,31,31,31,]),'NUMBER':([0,9,13,14,15,16,17,18,19,20,21,22,23,24,31,],[10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,]),'PI':([0,9,13,14,15,16,17,18,19,20,21,22,23,24,31,],[11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,]),'E':([0,9,13,14,15,16,17,18,19,20,21,22,23,24,31,],[12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,]),'$end':([1,2,3,4,5,6,7,8,10,11,12,27,29,30,32,33,34,35,36,37,38,39,40,41,42,43,],[0,-1,-2,-4,-17,-6,-20,-7,-21,-22,-23,-3,-15,-20,-16,-5,-18,-19,-8,-9,-10,-11,-12,-13,-14,-24,]),'OR':([2,4,6,8,10,11,12,25,27,33,36,37,38,39,40,41,42,43,],[13,-4,-6,-7,-21,-22,-23,13,-3,-5,-8,-9,-10,-11,-12,-13,-14,-24,]),'PLUS':([3,5,7,10,11,12,26,29,30,32,34,35,43,],[14,-17,-20,-21,-22,-23,14,-15,-20,-16,-18,-19,-24,]),'MINUS':([3,5,7,10,11,12,26,29,30,32,34,35,43,],[15,-17,-20,-21,-22,-23,15,-15,-20,-16,-18,-19,-24,]),'RPAREN':([4,5,6,7,8,10,11,12,25,26,27,29,30,32,33,34,35,36,37,38,39,40,41,42,43,],[-4,-17,-6,-20,-7,-21,-22,-23,42,43,-3,-15,-20,-16,-5,-18,-19,-8,-9,-10,-11,-12,-13,-14,-24,]),'AND':([4,6,8,10,11,12,27,33,36,37,38,39,40,41,42,43,],[16,-6,-7,-21,-22,-23,16,-5,-8,-9,-10,-11,-12,-13,-14,-24,]),'TIMES':([5,7,10,11,12,29,30,32,34,35,43,],[17,-20,-21,-22,-23,17,-20,17,-18,-19,-24,]),'DIVIDE':([5,7,10,11,12,29,30,32,34,35,43,],[18,-20,-21,-22,-23,18,-20,18,-18,-19,-24,]),'EQ':([7,10,11,12,28,43,],[19,-21,-22,-23,19,-24,]),'GT':([7,10,11,12,28,43,],[20,-21,-22,-23,20,-24,]),'LT':([7,10,11,12,28,43,],[21,-21,-22,-23,21,-24,]),'GE':([7,10,11,12,28,43,],[22,-21,-22,-23,22,-24,]),'LE':([7,10,11,12,28,43,],[23,-21,-22,-23,23,-24,]),'NE':([7,10,11,12,28,43,],[24,-21,-22,-23,24,-24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'expressionL':([0,9,],[2,25,]),'expressionA':([0,9,31,],[3,26,26,]),'termL':([0,9,13,],[4,4,27,]),'termA':([0,9,14,15,31,],[5,5,29,32,5,]),'factorL':([0,9,13,16,],[6,6,6,33,]),'factorA':([0,9,13,14,15,16,17,18,19,20,21,22,23,24,31,],[7,7,28,30,30,28,34,35,36,37,38,39,40,41,30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expressionL','expression',1,'p_expression','my_parser.py',15),
  ('expression -> expressionA','expression',1,'p_expression','my_parser.py',16),
  ('expressionL -> expressionL OR termL','expressionL',3,'p_expressionL','my_parser.py',21),
  ('expressionL -> termL','expressionL',1,'p_expressionL','my_parser.py',22),
  ('termL -> termL AND factorL','termL',3,'p_termL','my_parser.py',30),
  ('termL -> factorL','termL',1,'p_termL','my_parser.py',31),
  ('factorL -> BOOL','factorL',1,'p_factorL','my_parser.py',40),
  ('factorL -> factorA EQ factorA','factorL',3,'p_factorL','my_parser.py',41),
  ('factorL -> factorA GT factorA','factorL',3,'p_factorL','my_parser.py',42),
  ('factorL -> factorA LT factorA','factorL',3,'p_factorL','my_parser.py',43),
  ('factorL -> factorA GE factorA','factorL',3,'p_factorL','my_parser.py',44),
  ('factorL -> factorA LE factorA','factorL',3,'p_factorL','my_parser.py',45),
  ('factorL -> factorA NE factorA','factorL',3,'p_factorL','my_parser.py',46),
  ('factorL -> LPAREN expressionL RPAREN','factorL',3,'p_factorL','my_parser.py',47),
  ('expressionA -> expressionA PLUS termA','expressionA',3,'p_expressionA','my_parser.py',68),
  ('expressionA -> expressionA MINUS termA','expressionA',3,'p_expressionA','my_parser.py',69),
  ('expressionA -> termA','expressionA',1,'p_expressionA','my_parser.py',70),
  ('termA -> termA TIMES factorA','termA',3,'p_termA','my_parser.py',80),
  ('termA -> termA DIVIDE factorA','termA',3,'p_termA','my_parser.py',81),
  ('termA -> factorA','termA',1,'p_termA','my_parser.py',82),
  ('factorA -> NUMBER','factorA',1,'p_factorA','my_parser.py',93),
  ('factorA -> PI','factorA',1,'p_factorA','my_parser.py',94),
  ('factorA -> E','factorA',1,'p_factorA','my_parser.py',95),
  ('factorA -> LPAREN expressionA RPAREN','factorA',3,'p_factorA','my_parser.py',96),
]
